name: radial_slider
description: A radial slider widget.
version: 0.0.1
author: Amadeus <gliheng@gmail.com>
homepage: https://github.com/gliheng/radial_slider

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"

